version: '3.8'

services:
  webapp-client:
    build:
      context: client
      dockerfile: dockerfile
    container_name: my-client-container
    depends_on:
      - webapp-server
    ports:
      - "3000:3000"

  webapp-server:
    build:
      context: server
      dockerfile: dockerfile
    container_name: my-server-container
    restart: always
    ports:
      - "7777:7777"
    depends_on:
      - postgres

  postgres:
    image: 'postgres:12'
    container_name: my-postgres-container
    restart: always
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


