import { createSlice } from '@reduxjs/toolkit';
import commonReducer from 'utils/commonReducer';
import { TAB_NAMES } from 'constants/tabs';
import type { ExclusiveState } from './types';

export const initialState: ExclusiveState = {
  [TAB_NAMES.EXCLUSIVES]: [
    {
      id: 1,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(new Date().getDate() + 1)),
        new Date(new Date().setDate(new Date().getDate() + 2)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
    {
      id: 2,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
    {
      id: 3,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
    {
      id: 4,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
    {
      id: 5,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
    {
      id: 6,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
    {
      id: 7,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
    {
      id: 8,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
    {
      id: 9,
      address: 'летная 11',
      typeOfHouse: 'дом',
      floor: 2,
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      reservePrice: 27000,
      startPrice: 27000,
      endPrice: 27000,
      preSalePrepare: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      adStart: '20.06.2021',
      incomingCalls: 22,
      incomingSocial: 21,
      crmNumberAndDescriptionOfClient: 'какая-то информация',
      watchingDays: [
        new Date(),
        new Date(new Date().setDate(24)),
        new Date(new Date().setDate(24)),
      ],
      signUpForView: 15,
      visited: 12,
      offers: 10,
      deposit: '20.06.2021',
      deal: '10.06.2021',
      commission: 2500,
      adCost: 12564,
    },
  ],
  selectedCells: [],
  selectedAll: false,
};

const reducers = commonReducer();

export const exclusiveSlice = createSlice({
  name: 'flats',
  initialState,
  reducers,
});

export const {
  handleRemoveCell,
  handleAllCells,
  handleAddCell,
  handleSelectedAll,
} = exclusiveSlice.actions;

export default exclusiveSlice.reducer;
