import { HeadColumnType } from 'pages/InfoTables/common/Table/types';

export const TABLE_COLUMNS: Omit<HeadColumnType, 'onClick'>[] = [
  { id: 39, value: 'id', title: '№' },
  { id: 40, value: 'address', title: 'адрес' },
  { id: 41, value: 'typeOfHouse', title: 'тип' },
  { id: 42, value: 'floor', title: 'этаж' },
  { id: 43, value: 'area', title: 'площадь' },
  { id: 44, value: 'description', title: 'описание объекта' },
  { id: 45, value: 'reservePrice', title: 'цена резервная' },
  { id: 46, value: 'startPrice', title: 'цена стартовая' },
  { id: 47, value: 'endPrice', title: 'цена конечная' },
  { id: 48, value: 'preSalePrepare', title: 'предпродажная подготовка' },
  { id: 49, value: 'adStart', title: 'старт рекламы' },
  { id: 50, value: 'incomingCalls', title: 'входящие звонки' },
  { id: 51, value: 'incomingSocial', title: 'входящие соцсети' },
  {
    id: 52,
    value: 'crmNumberAndDescriptionOfClient',
    title: '№ в срм анкета клиента',
  },
  { id: 53, value: 'watchingDays', title: 'дни показов' },
  { id: 54, value: 'signUpForView', title: 'записались на просмотр' },
  { id: 55, value: 'visited', title: 'пришли' },
  { id: 56, value: 'offers', title: 'оферты к-во' },
  { id: 57, value: 'deposit', title: 'задаток' },
  { id: 58, value: 'deal', title: 'сделка' },
  { id: 59, value: 'commission', title: 'комиссия' },
  { id: 60, value: 'adCost', title: 'расход рекламы(грн.)' },
];
