import { createSlice } from '@reduxjs/toolkit';
import commonReducer from 'utils/commonReducer';
import { TAB_NAMES } from 'constants/tabs';
import type { FlatsState } from './types';

export const initialState: FlatsState = {
  [TAB_NAMES.FLATS]: [
    {
      id: 1,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGave: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: new Date().toLocaleDateString(),
      dateOfStartAd: new Date().toLocaleDateString(),
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 3,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGave: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: new Date().toLocaleDateString(),
      dateOfStartAd: new Date().toLocaleDateString(),
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 2,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGave: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: new Date().toLocaleDateString(),
      dateOfStartAd: new Date().toLocaleDateString(),
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 4,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGave: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: new Date().toLocaleDateString(),
      dateOfStartAd: new Date().toLocaleDateString(),
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 5,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGave: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: new Date().toLocaleDateString(),
      dateOfStartAd: new Date().toLocaleDateString(),
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 6,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGave: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: new Date().toLocaleDateString(),
      dateOfStartAd: new Date().toLocaleDateString(),
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 7,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGave: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: new Date().toLocaleDateString(),
      dateOfStartAd: new Date().toLocaleDateString(),
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 8,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      area: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGave: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: new Date().toLocaleDateString(),
      dateOfStartAd: new Date().toLocaleDateString(),
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
  ],
  selectedCells: [],
  selectedAll: false,
};

const reducers = commonReducer();

export const flatsSlice = createSlice({
  name: 'flats',
  initialState,
  reducers,
});

export const {
  handleRemoveCell,
  handleAllCells,
  handleAddCell,
  handleSelectedAll,
} = flatsSlice.actions;

export default flatsSlice.reducer;
