import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import type { CounterState } from './types';

const initialState: CounterState = {
  flats: [
    {
      id: 1,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      square: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGive: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: '20.06.2021',
      dateOfStartAd: '20.06.2021',
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 3,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      square: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGive: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: '20.06.2021',
      dateOfStartAd: '20.06.2021',
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 2,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      square: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGive: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: '20.06.2021',
      dateOfStartAd: '20.06.2021',
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 4,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      square: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGive: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: '20.06.2021',
      dateOfStartAd: '20.06.2021',
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 5,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      square: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGive: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: '20.06.2021',
      dateOfStartAd: '20.06.2021',
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 6,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      square: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGive: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: '20.06.2021',
      dateOfStartAd: '20.06.2021',
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 7,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      square: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGive: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: '20.06.2021',
      dateOfStartAd: '20.06.2021',
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
    {
      id: 8,
      address: 'летная 11',
      floor: 2,
      numberOfStoreys: 5,
      buildingMaterial: 'панель',
      typeOfHouse: 'моск проэкт',
      square: 47,
      description: 'м\\п окна, жилое сост. Аккуратная',
      price: 27000,
      pricePerMeter: 574,
      commission: 500,
      number: '063-8745202',
      whoGive: 'ан благострой',
      stateOfLid: 'срочная продажа',
      descriptionOfClient: 'с ан не работает',
      managerOfObject: 'Татьяна',
      dateOfSold: '20.06.2021',
      dateOfStartAd: '20.06.2021',
      soldPrice: 27000,
      quantityOfRooms: 4,
    },
  ],
  selectedCells: [],
};

export const flatsSlice = createSlice({
  name: 'flats',
  initialState,
  reducers: {
    handleAddCell: (state, action: PayloadAction<number>) => {
      const { payload } = action;

      state.selectedCells.push(payload);
    },
    handleRemoveCell: (state, action: PayloadAction<number>) => {
      const { payload } = action;

      state.selectedCells = state.selectedCells.filter(
        item => item !== payload
      );
    },
    handleAllCells: (state, action: PayloadAction<number[]>) => {
      const { payload } = action;

      state.selectedCells = payload;
    },
  },
});

export const { handleRemoveCell, handleAllCells, handleAddCell } =
  flatsSlice.actions;

export default flatsSlice.reducer;
